// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdsmwjeantrclnhwidmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkc213amVhbnRyY2xuaHdpZG11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODYzMzMsImV4cCI6MjA2NjI2MjMzM30.HeJ-TTSgWtzcylCUwu5qqUOcEl38UELMSMQs7S_cCWo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);